### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by peachy-ch** [websylv/homeassistant-meteoswiss#10] opened 2020-05-06 05:26 UTC
2020-05-06 07:24:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for meteo-swiss doing I/O at custom_components/meteo-swiss/meteoswiss/msData.py, line 26: tmp = s.get(baseUrl)

**Comment by websylv** [comment] 2020-05-08 10:25
Duplicate of #7

**Closed by websylv** 2020-05-08 10:25 UTC
