### ISSUE TITLE
Showing current day instead of next one for the forecast

### ISSUE THREAD

**Issue by nadworny** [websylv/homeassistant-meteoswiss#9] opened 2020-05-02 08:24 UTC
Thanks a lot for MeteoSwiss provider - it's awesome!

Would it be possible to get the current day being displayed in the forecast as well? Same as dark sky has it?
![image](https://user-images.githubusercontent.com/1425919/80859200-06acef80-8c5f-11ea-853b-99084166453f.png)

MeteoSwiss shows the next day (Sunday) instead of current (Saturday). Showing current day is useful to get the high/low temps.
![image](https://user-images.githubusercontent.com/1425919/80859161-c9e0f880-8c5e-11ea-8270-e937079d18fb.png)

I've tried to implement it by combining the simple weather card component as there you can choose "extrema" attribute to display high/low temps but it's the same problem - it shows the high/low for the next day only...
![image](https://user-images.githubusercontent.com/1425919/80859206-188e9280-8c5f-11ea-9700-ccb6b2732de7.png)

**Comment by websylv** [comment] 2020-05-02 18:50
i working on full rewrite.
it will take some time probably but i will add the option for hourly i know how to get from MS for the moment the issue is more to understand how i can implement in HomeAssistant the documentation for delvelopper is limited

**Comment by websylv** [comment] 2020-05-17 08:36
Duplicate of #5

**Closed** 2020-05-17 08:37 UTC
Labels: enhancement
